language: node_js
node_js:
  - lts/*
install: 
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: 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
  keep_history: true
  on:
    branch: master
